### ISSUE TITLE
Publish a npm package

### ISSUE THREAD

**Issue by ehmicky** [pizzafox/netlify-cache-nextjs#15]
Amazing package!

Would it be possible to publish it to npm? This Netlify Build plugin would be very useful to lots of people.

The [official documentation](https://github.com/netlify/build/blob/master/docs/creating-a-plugin.md#publishing-a-plugin) includes few recommendation on naming and tagging to make sure your plugin will be easy to find.

**Comment by pizzafox** [comment]
Published [here](https://www.npmjs.com/package/netlify-plugin-cache-nextjs), under the `netlify-plugin-cache-nextjs` package name.

**Comment by ehmicky** [comment]
Thanks @pizzafox, that's great!
I have added to Netlify's plugin repository: https://github.com/netlify/plugins/pull/3
