### ISSUE TITLE
Seeing "No build cache found" warnings after plugin was enabled

### ISSUE THREAD

**Issue by alexshyba** [pizzafox/netlify-cache-nextjs#31]
Hello,

Super eager to get this working, thanks making this plugin available!

Following the docs, added the [plugin to the netlify.toml file](https://github.com/alexshyba/nextjs-sandbox/blob/master/netlify.toml), triggered two builds to ensure the `.next` artifacts got cached but still seeing this warning in the build logs:

```
1:31:52 PM: Warning: No build cache found. Please configure build caching for faster rebuilds. Read more: https://err.sh/next.js/no-cache
```

- Is the module dependent on a particular version of Next.js?
- Do I need to sign up for Netlify Build Plugins to enable it on my account?

[My sandbox repo with vanilla next.js](https://github.com/alexshyba/nextjs-sandbox).

Thanks!

**Comment by pizzafox** [comment]
The module caches the `.next` folder. If the plugin is running the only reason it wouldn't be caching is if you had configured [a custom the build directory](https://nextjs.org/docs/api-reference/next.config.js/setting-a-custom-build-directory) (which you didn't).

Most likely the plugin is *not* running since you aren't in [the plugins beta](https://www.netlify.com/build/plugins-beta/). You can [join the beta on Netlify's form](https://forms.gle/RemZEGP35P8fEL848)

**Comment by alexshyba** [comment]
Thank you so much for the prompt response!
Just signed up and enabled plugins on this site. Getting this error now:

```
2:49:53 PM: ❯ Installing plugins
2:49:53 PM:    - netlify-plugin-cache-nextjs
2:49:53 PM: ​
2:50:01 PM: ​
2:50:01 PM: ┌─────────────────────────────┐
2:50:01 PM: │     Core internal error     │
2:50:01 PM: └─────────────────────────────┘
2:50:01 PM: ​
2:50:01 PM: ❯ Error message
2:50:01 PM:   Error: Cannot find module 'netlify-plugin-cache-nextjs' from '/opt/build/repo'​
2:50:01 PM: ​
2:50:01 PM: ❯ Error location
2:50:01 PM:       at /opt/buildhome/.nvm/versions/node/v12.16.1/lib/node_modules/@netlify/build/node_modules/resolve/lib/async.js:107:35
2:50:01 PM:       at processDirs (/opt/buildhome/.nvm/versions/node/v12.16.1/lib/node_modules/@netlify/build/node_modules/resolve/lib/async.js:260:39)
2:50:01 PM:       at isdir (/opt/buildhome/.nvm/versions/node/v12.16.1/lib/node_modules/@netlify/build/node_modules/resolve/lib/async.js:267:32)
2:50:01 PM:       at /opt/buildhome/.nvm/versions/node/v12.16.1/lib/node_modules/@netlify/build/node_modules/resolve/lib/async.js:23:69
2:50:01 PM:       at FSReqCallback.oncomplete (fs.js:166:21)​
2:50:01 PM: ​
2:50:01 PM: ❯ Error properties
2:50:01 PM:   { code: 'MODULE_NOT_FOUND' }
2:50:01 PM: ​
```
[Full build log here](https://app.box.com/s/2r1nlqzwwfd9hiiupakznql4bi3yh3il).

Thanks again!

**Comment by alexshyba** [comment]
Not sure if this helps, but I swapped out the plugin name with `netlify-plugin-a11` and it got installed successfully on this site. 
```
3:11:45 PM: ❯ Loading plugins
3:11:45 PM:    - netlify-plugin-a11y@0.0.6
```

For `netlify-plugin-cache-nextjs` it still shows "Cannot find module"

**Comment by pizzafox** [comment]
That's weird. I'm guessing this has something to do with how the package is published on the npm, Inc. registry. I will investigate.
