### ISSUE TITLE
Warning: No build cache found

### ISSUE THREAD

**Issue by alexshyba** [pizzafox/netlify-cache-nextjs#34]
Hello and thanks again for prompt fixes! Looks like we are getting close.

I see this sequence in the logs and the build cache doesn't appear to be active. Ran multiple builds, Next.js shows the warning with "no build cache found". 
```
8:58:42 PM:  ✔  netlify-plugin-cache-nextjs onPreBuild completed in 8ms
..
8:59:02 PM: Warning: No build cache found. Please configure build caching for faster rebuilds. Read more: https://err.sh/next.js/no-cache
...
8:59:02 PM: ┌─────────────────────────────────────────────────────────────────┐
8:59:02 PM: │ 3. Running onPostBuild command from netlify-plugin-cache-nextjs │
8:59:02 PM: └─────────────────────────────────────────────────────────────────┘
8:59:02 PM: ​
8:59:02 PM: ​
8:59:02 PM:  ✔  netlify-plugin-cache-nextjs onPostBuild completed in 4ms
8:59:02 PM: ​
8:59:02 PM: ┌─────────────────────────────┐
8:59:02 PM: │   Netlify Build Complete    │
8:59:02 PM: └─────────────────────────────┘
8:59:02 PM: ​
8:59:02 PM:  ✔  Netlify Build completed in 21847ms
```

[Complete build log](https://app.box.com/s/583i2k3c7vzw95wzw5rlzkgqhxsr7nl4).
Still trying [on this repo.](https://github.com/alexshyba/nextjs-sandbox)

Do you happen to have a test repo you tested this with, so I can take a look and compare the code?
Otherwise, any ideas how to troubleshoot? Happy to help, just don't know where to even look.

**Comment by pizzafox** [comment]
This is an interesting bug. The entire project is 32 LoC and is nearly a copy-paste of the example Netlify gave for cache plugins. For Next.js to say nothing is being cached even after the script is being run makes narrows the bug down to one explanation:

The cache folder is being applied somewhere it doesn't belong. I will refactor the path generation sections following [the method](https://github.com/jlengstorf/netlify-plugin-gatsby-cache/blob/947be7f885e5a55aa90b6010f04439fe9c6e890b/index.js#L3-L6) a similar plugin for caching Gatsby used.

**Comment by pizzafox** [comment]
Commit 537c0619f76fa6c6cc8e4e703f7c639eadb09de3 should have fixed this, however I am getting the same as you are on one of my sites. I will investigate further.

**Comment by alexshyba** [comment]
Thank you! 1.2.2 fixed the issue, I am seeing 1 minute shaved off from 4 minute builds and the next.js warning is gone. FYI - I had to disable the plugins in Netlify for this site and re-enable it, otherwise the site was pulling older version of this plugin.
Thanks again for your work and speedy resolution!
