### ISSUE TITLE
Configure .next folder location

### ISSUE THREAD

**Issue by oliviertassinari** [pizzafox/netlify-cache-nextjs#40]
I'm looking into an integration of the plugin in https://github.com/mui-org/material-ui/pull/20349.
I have hit a roadblock. We don't host the .next folder at the same location as Netlify's base folder.
Would it be possible to make the location configurable? It seems that plugins have a way to add arguments: https://docs.netlify.com/configure-builds/build-plugins/#install-a-plugin.

**Comment by pizzafox** [comment]
I will add a way to configure this in the next release. Should take about 30 minutes.

**Comment by oliviertassinari** [comment]
@pizzafox You rock, thanks you!
