### ISSUE TITLE
Idea: create a Netlify deployement on the repository as a end-to-end test

### ISSUE THREAD

**Issue by oliviertassinari** [pizzafox/netlify-cache-nextjs#53]
I was looking at the pull request CI, it seems that there is an opportunity to avoid regressions between releases, it won't be the best safeguard, but it could help a bit.

**Comment by pizzafox** [comment]
Whatever I did seems to have completely broken the GitHub Actions pipeline and now nothing runs.

**Comment by oliviertassinari** [comment]
I can't see a Netlify deployment running on each pull request. Should I assume you did not push the idea further?

**Comment by pizzafox** [comment]
The local tests should be running [here](https://github.com/pizzafox/netlify-cache-nextjs/runs/635223154?check_suite_focus=true). I would like to implement some type of actual test that runs on Netlify.com but I worry it'll burn

**Comment by oliviertassinari** [comment]
Thank for the update :)
