### ISSUE TITLE
.next/cache not found from one "Deploy Site" to the next

### ISSUE THREAD

**Issue by moop-moop** [pizzafox/netlify-cache-nextjs#80]
Using the web GUI installation of the plugin on a Netlify Site....
Should the "Deploy Site" under the Retry Deploy take advantage of the .next/cache?
Obviously the "Clear cache and deploy site" would remove any caching.

My logs are indicating that the .next/cache is saved every time by the plugin, but then never found on the next deploy.

Attached is a log to check out, our Netlify log is not public.
[netlify.log](https://github.com/pizzafox/netlify-cache-nextjs/files/4956892/netlify.log)

**Comment by pizzafox** [comment]
After the cache has been stored at the end of a successful build subsequent builds should use the cache, and retrying a build should be no exception to this.
Does retrying the build again use the cache properly?

**Comment by moop-moop** [comment]
> After the cache has been stored at the end of a successful build subsequent builds should use the cache, and retrying a build should be no exception to this.
> Does retrying the build again use the cache properly?

It does seem to. The log I attached was a 3rd in a row Deploy without clearing the cache and deploying. 
The logs says .next/cache not found. 
I am only using default next.js folder paths. I'll post our next.js config after this.

**Comment by moop-moop** [comment]
> > After the cache has been stored at the end of a successful build subsequent builds should use the cache, and retrying a build should be no exception to this.
> > Does retrying the build again use the cache properly?
> 
> It does not seem to. The log I attached was a 3rd in a row Deploy without clearing the cache and deploying. 
> The logs says .next/cache not found. 
> I am only using default next.js folder paths. I'll post our next.js config after this. 

```javascript
module.exports = {
  generateBuildId: async () => {
    return process.env.COMMIT_REF || 'build';
  },
  target: 'serverless',
  cssModules: true,
};

```

**Comment by pizzafox** [comment]
Could you try making a minimal reproduction repository? I'm not sure what's going wrong, and I haven't seen anything like this before.

**Comment by pizzafox** [comment]
Can you try another build with the latest version (`v1.5.0`)?

**Comment by moop-moop** [comment]
> 
> 
> Can you try another build with the latest version (`v1.5.0`)?

I did and am still seeing the `.next/cache` directory not being found....

```console
1:36:23 PM: ┌────────────────────────────────────────────────────────┐
1:36:23 PM: │ 2. onPreBuild command from netlify-plugin-cache-nextjs │
1:36:23 PM: └────────────────────────────────────────────────────────┘
1:36:23 PM: ​
1:36:23 PM: .next/cache does not exist on disk
1:36:23 PM: Couldn't restore the cache for the .next folder at the location `.next/cache`

1:36:23 PM: (netlify-plugin-cache-nextjs onPreBuild completed in 216ms)
1:37:29 PM: ┌─────────────────────────────────────────────────────────┐
1:37:29 PM: │ 6. onPostBuild command from netlify-plugin-cache-nextjs │
1:37:29 PM: └─────────────────────────────────────────────────────────┘
1:37:29 PM: ​
1:37:29 PM: .next/cache exists on disk
1:37:29 PM: Cached the .next folder at the location `.next/cache`
```

**Comment by moop-moop** [comment]
I'll create a minimal public repo to build and share as soon as I can.

**Comment by moop-moop** [comment]
Well locally with `netlify build --develop` everything worked correctly:
```console
┌────────────────────────────────────────────────────────┐
│ 2. onPreBuild command from netlify-plugin-cache-nextjs │
└────────────────────────────────────────────────────────┘
​
.next\cache exists on disk
Restored the cached .next folder at the location `.next\cache`
```

**Comment by pizzafox** [comment]
That makes me think this is a Netlify side issue. Try sending them [a support request](https://www.netlify.com/support/) and feel free to include me in the ticket. My email is jonah@jonah.pw.

**Comment by pizzafox** [comment]
Any updates?

**Comment by pizzafox** [comment]
Closed because inactive and probably an upstream issue.

**Comment by moop-moop** [comment]
> 
> 
> Any updates?

The issue disappeared though there was no significant changes on my end or with versions of anything.
Very strange, but I can't reproduce now. 
I have not seen anything for ~3 weeks.

**Comment by pmourer** [comment]
We are currently getting this issue under the same circumstances -- we have the package included in our netlify.toml and that is all we have done. We are using `next-on-netlify` to enable serverless functions if that is relevant. Is there any further discovery as to what resolved this?

**Comment by pmourer** [comment]
I did not previously have the plugin installed in Netlify itself, just declared in our repo -- is this necessary? this was not clear from the docs.

However, I am still receiving the message.

**Comment by pmourer** [comment]
and one last thing -- similarly, locally it appears to work (on second build)
```
$ netlify build --context=deploy-preview
...
┌────────────────────────────────────────────────────────┐
│ 1. onPreBuild command from netlify-plugin-cache-nextjs │
└────────────────────────────────────────────────────────┘

.next/cache exists on disk
Restored the cached .next folder at the location `.next/cache`

(netlify-plugin-cache-nextjs onPreBuild completed in 323ms)
```

**Comment by pizzafox** [comment]
Please move to #95.
